/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.EventQueue;

/**
 *
 * @author bunhu
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        setBackground(new Color(0,0,0,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconSach = new javax.swing.JLabel();
        lblSach = new javax.swing.JLabel();
        BtnSach = new javax.swing.JLabel();
        iconDG = new javax.swing.JLabel();
        lblDocGia = new javax.swing.JLabel();
        BtnDocGia = new javax.swing.JLabel();
        BtnSach1 = new javax.swing.JLabel();
        BtnSach2 = new javax.swing.JLabel();
        BtnMuonSach = new javax.swing.JLabel();
        BtnSach5 = new javax.swing.JLabel();
        BtnSach6 = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JLabel();
        MenuBtn = new javax.swing.JLabel();
        TKBtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý thư viện");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        iconSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_books_64px.png"))); // NOI18N
        getContentPane().add(iconSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 120, 90));

        lblSach.setBackground(new java.awt.Color(226, 243, 245));
        lblSach.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblSach.setForeground(new java.awt.Color(153, 153, 153));
        lblSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSach.setText("Quản lý sách");
        lblSach.setOpaque(true);
        getContentPane().add(lblSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 140, 60));

        BtnSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Categories.png"))); // NOI18N
        BtnSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSachMouseClicked(evt);
            }
        });
        getContentPane().add(BtnSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 160, 180));

        iconDG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_member_64px.png"))); // NOI18N
        getContentPane().add(iconDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 120, 90));

        lblDocGia.setBackground(new java.awt.Color(226, 243, 245));
        lblDocGia.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblDocGia.setForeground(new java.awt.Color(153, 153, 153));
        lblDocGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDocGia.setText("<html>Quản lý đọc</br>    giả</html>");
        lblDocGia.setOpaque(true);
        getContentPane().add(lblDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 130, 60));

        BtnDocGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Categories.png"))); // NOI18N
        getContentPane().add(BtnDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 160, 180));

        BtnSach1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnSach1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Categories.png"))); // NOI18N
        getContentPane().add(BtnSach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 160, 180));

        BtnSach2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnSach2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Categories.png"))); // NOI18N
        getContentPane().add(BtnSach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 160, 180));

        BtnMuonSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnMuonSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Categories.png"))); // NOI18N
        getContentPane().add(BtnMuonSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 160, 180));

        BtnSach5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnSach5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Categories.png"))); // NOI18N
        getContentPane().add(BtnSach5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 160, 180));

        BtnSach6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnSach6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Categories.png"))); // NOI18N
        getContentPane().add(BtnSach6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 160, 180));

        Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/study.png"))); // NOI18N
        getContentPane().add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 130));

        LogoutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogoutButton.png"))); // NOI18N
        LogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 100, 40));

        MenuBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        MenuBtn.setForeground(new java.awt.Color(255, 255, 255));
        MenuBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_menu_24px.png"))); // NOI18N
        MenuBtn.setText("Menu");
        MenuBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        MenuBtn.setDisabledIcon(null);
        MenuBtn.setIconTextGap(10);
        getContentPane().add(MenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 216, 50));

        TKBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        TKBtn.setForeground(new java.awt.Color(255, 255, 255));
        TKBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TKBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_bar_chart_30px.png"))); // NOI18N
        TKBtn.setText("Thống kê");
        TKBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        TKBtn.setIconTextGap(10);
        getContentPane().add(TKBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 216, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 20, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NavBar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 520));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainPanel.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 720, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        EventQueue.invokeLater(new Runnable() {
                public void run() {
                        try {
                            
                            Login frame = new Login();
                            frame.setVisible(true);
                        } catch (Exception e) {
                                e.printStackTrace();
                        }
                }
        });
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void BtnSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSachMouseClicked
        // TODO add your handling code here:
        this.dispose();
        EventQueue.invokeLater(new Runnable() {
                public void run() {
                        try {
                            
                            QlySachForm frame = new QlySachForm();
                            frame.setVisible(true);
                        } catch (Exception e) {
                                e.printStackTrace();
                        }
                }
        });
    }//GEN-LAST:event_BtnSachMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnDocGia;
    private javax.swing.JLabel BtnMuonSach;
    private javax.swing.JLabel BtnSach;
    private javax.swing.JLabel BtnSach1;
    private javax.swing.JLabel BtnSach2;
    private javax.swing.JLabel BtnSach5;
    private javax.swing.JLabel BtnSach6;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel LogoutButton;
    private javax.swing.JLabel MenuBtn;
    private javax.swing.JLabel TKBtn;
    private javax.swing.JLabel iconDG;
    private javax.swing.JLabel iconSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDocGia;
    private javax.swing.JLabel lblSach;
    // End of variables declaration//GEN-END:variables
}
